name: Testes Java

on:
  workflow_dispatch:

  pull_request:

  push:

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Executar testes
        working-directory: ./aula09
        run: mvn test